import type { BattleCardDef } from "./types";

/** Карты 9–33 по [`DECK.md`](../../docs/DECK.md) — упрощённые эффекты для прототипа */
export const EXTENDED_CARD_DEFS: BattleCardDef[] = [
  {
    id: "deck_window_gaze",
    name: "Взгляд в окно",
    cost: 1,
    icon: "🪟",
    desc: "+4 ОЗ (спокойствие).",
    needsEnemyTarget: false,
    kind: "utility",
    healPlayer: 4,
    deckCategory: "acceptance",
  },
  {
    id: "deck_hand_shoulder",
    name: "Рука на плече (своя)",
    cost: 1,
    icon: "🤲",
    desc: "+2 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 2,
    deckCategory: "acceptance",
  },
  {
    id: "deck_done_list",
    name: "Список «уже сделанного»",
    cost: 2,
    icon: "✓",
    desc: "Урон по врагу: по одному за карту в руке (до 5).",
    needsEnemyTarget: true,
    kind: "attack",
    damageFromHandSize: { cap: 5 },
    deckCategory: "acceptance",
  },
  {
    id: "silence_accept",
    name: "Тишина (принятие)",
    cost: 2,
    icon: "🤫",
    desc: "При пути принятия 4+ — конец боя без добивания. Иначе +2 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    instantWinIfAcceptanceAtLeast: 4,
    block: 2,
    deckCategory: "acceptance",
  },
  {
    id: "deck_permission",
    name: "Разрешение",
    cost: 1,
    icon: "🌿",
    desc: "+3 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 3,
    deckCategory: "acceptance",
  },
  {
    id: "deck_grit_teeth",
    name: "Сжать зубы",
    cost: 2,
    icon: "😬",
    desc: "5 урона врагу. Ты теряешь 2 ОЗ.",
    needsEnemyTarget: true,
    kind: "attack",
    damage: 5,
    selfDamageAfterHit: 2,
    deckCategory: "absorption",
  },
  {
    id: "deck_autopilot",
    name: "Режим «автопилот»",
    cost: 1,
    icon: "⚙",
    desc: "+2 энергии.",
    needsEnemyTarget: false,
    kind: "utility",
    addEnergy: 2,
    deckCategory: "absorption",
  },
  {
    id: "deck_louder",
    name: "Громче!",
    cost: 2,
    icon: "📢",
    desc: "8 урона. Следующий ход пропускаешь.",
    needsEnemyTarget: true,
    kind: "attack",
    damage: 8,
    skipNextPlayerTurn: true,
    deckCategory: "absorption",
  },
  {
    id: "deck_wall_card",
    name: "Стена",
    cost: 3,
    icon: "🧱",
    desc: "+8 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 8,
    deckCategory: "absorption",
  },
  {
    id: "deck_not_now",
    name: "Не сейчас",
    cost: 1,
    icon: "⏸",
    desc: "+6 блока, возьми 1 карту.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 6,
    draw: 1,
    deckCategory: "absorption",
  },
  {
    id: "deck_background_noise",
    name: "Фоновый шум",
    cost: 1,
    icon: "〰",
    desc: "+1 блок (интеграция: гул).",
    needsEnemyTarget: false,
    kind: "utility",
    block: 1,
    deckCategory: "integration",
  },
  {
    id: "deck_inner_advisor",
    name: "Внутренний советчик",
    cost: 1,
    icon: "💬",
    desc: "+1 энергия.",
    needsEnemyTarget: false,
    kind: "utility",
    addEnergy: 1,
    deckCategory: "integration",
  },
  {
    id: "deck_own_path",
    name: "Своя тропа",
    cost: 1,
    icon: "🛤",
    desc: "+2 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 2,
    deckCategory: "integration",
  },
  {
    id: "deck_companion",
    name: "Спутница",
    cost: 1,
    icon: "🌑",
    desc: "+3 ОЗ.",
    needsEnemyTarget: false,
    kind: "utility",
    healPlayer: 3,
    deckCategory: "integration",
  },
  {
    id: "deck_night_talk",
    name: "Ночной разговор",
    cost: 1,
    icon: "🌙",
    desc: "+1 энергия, +2 ОЗ.",
    needsEnemyTarget: false,
    kind: "utility",
    addEnergy: 1,
    healPlayer: 2,
    deckCategory: "integration",
  },
  {
    id: "deck_own_eyes",
    name: "Свои глаза",
    cost: 1,
    icon: "👁",
    desc: "+2 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 2,
    deckCategory: "integration",
  },
  {
    id: "deck_card_vera",
    name: "Карта Веры",
    cost: 1,
    icon: "🗺",
    desc: "Возьми 2 карты.",
    needsEnemyTarget: false,
    kind: "utility",
    draw: 2,
    deckCategory: "npc",
  },
  {
    id: "deck_sapling",
    name: "Саженец",
    cost: 1,
    icon: "🌱",
    desc: "+5 ОЗ.",
    needsEnemyTarget: false,
    kind: "utility",
    healPlayer: 5,
    deckCategory: "npc",
  },
  {
    id: "deck_flowers_roots",
    name: "Цветы у корней",
    cost: 1,
    icon: "🌷",
    desc: "+4 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 4,
    deckCategory: "npc",
  },
  {
    id: "deck_echo_echo",
    name: "Эхо",
    cost: 2,
    icon: "🔁",
    desc: "+4 ОЗ.",
    needsEnemyTarget: false,
    kind: "utility",
    healPlayer: 4,
    deckCategory: "npc",
  },
  {
    id: "deck_quiet_voice",
    name: "Тихий голос",
    cost: 1,
    icon: "🕯",
    desc: "+2 блока.",
    needsEnemyTarget: false,
    kind: "utility",
    block: 2,
    deckCategory: "npc",
  },
  {
    id: "deck_trail_follow",
    name: "След",
    cost: 1,
    icon: "👣",
    desc: "+3 блока (редкая).",
    needsEnemyTarget: false,
    kind: "utility",
    block: 3,
    deckCategory: "rare",
  },
  {
    id: "silence_finale",
    name: "Тишина (редкая)",
    cost: 3,
    icon: "✶",
    desc: "Если все враги поняты — особый исход в финале.",
    needsEnemyTarget: false,
    kind: "utility",
    healPlayer: 1,
    deckCategory: "rare",
  },
  {
    id: "deck_edge",
    name: "Край",
    cost: 2,
    icon: "⚡",
    desc: "Следующая твоя атака +3 урона.",
    needsEnemyTarget: false,
    kind: "buff",
    addBonusDamageNextAttack: 3,
    deckCategory: "rare",
  },
  {
    id: "deck_stand",
    name: "Стоять",
    cost: 1,
    icon: "🜂",
    desc: "+1 блок за каждого понятого врага (до +6).",
    needsEnemyTarget: false,
    kind: "utility",
    deckCategory: "rare",
  },
];
