import { LevelData } from './types';

export const fireflyVillage: LevelData = {
  id: 'fireflyVillage',
  name: 'Деревня Огоньков',
  width: 3600,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 154 },
    { x: 400, y: 152 },
    { x: 800, y: 154 },
    { x: 1200, y: 150 },
    { x: 1600, y: 152 },
    { x: 2000, y: 150 },
    { x: 2400, y: 152 },
    { x: 2800, y: 150 },
    { x: 3200, y: 152 },
    { x: 3600, y: 154 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.15 },
    { key: 'bg-trees', scrollFactor: 0.35 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'glasha-teahouse',
      type: 'ritual',
      x: 400,
      spriteKey: 'object',
      name: 'Чайная бабушки Глаши',
      ritualId: 'tea-silence',
    },
    {
      id: 'mila-herbalist',
      type: 'npc',
      x: 800,
      spriteKey: 'npc',
      name: 'Мила',
      dialogueId: 'mila-village',
    },
    {
      id: 'yarik-workshop',
      type: 'npc',
      x: 1300,
      spriteKey: 'npc',
      name: 'Кузнец Ярик',
      dialogueId: 'yarik-village',
    },
    {
      id: 'tom-musician',
      type: 'npc',
      x: 1800,
      spriteKey: 'npc',
      name: 'Том',
      dialogueId: 'tom-village',
    },
    {
      id: 'polina-library',
      type: 'examine',
      x: 2300,
      spriteKey: 'object',
      name: 'Библиотека Полины',
      examineText: 'Крошечная библиотека в переоборудованном сарае. Книги потрёпанные, с загнутыми страницами. На полке — табличка: «Ты не выбираешь книгу. Она выбирает тебя.»',
    },
    {
      id: 'community-garden',
      type: 'ritual',
      x: 2800,
      spriteKey: 'object',
      name: 'Общинный сад',
      ritualId: 'garden-care',
    },
    {
      id: 'exit-to-river',
      type: 'transition',
      x: 3500,
      spriteKey: 'object',
      name: 'Тропа к реке',
      targetLevel: 'quietRiver',
    },
  ],
  palette: {
    bg: '#1e1a14',
    accent: '#E0B87A',
    fog: '#2e2418',
  },
};
