import { LevelData } from './types';

export const fireflyVillage: LevelData = {
  id: 'fireflyVillage',
  name: 'Деревня Огоньков',
  width: 3600,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 154 },
    { x: 400, y: 152 },
    { x: 800, y: 154 },
    { x: 1200, y: 150 },
    { x: 1600, y: 152 },
    { x: 2000, y: 150 },
    { x: 2400, y: 152 },
    { x: 2800, y: 150 },
    { x: 3200, y: 152 },
    { x: 3600, y: 154 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.15 },
    { key: 'bg-trees', scrollFactor: 0.35 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'glasha',
      type: 'npc',
      x: 400,
      spriteKey: 'npc',
      name: 'Бабушка Глаша',
      dialogueId: 'glasha-teahouse',
    },
    {
      id: 'glasha-tea-ritual',
      type: 'ritual',
      x: 440,
      spriteKey: 'object',
      name: 'Чашка чая',
      ritualId: 'tea-silence',
      conditionFlag: 'glasha-tea-accepted',
      conditionNotFlag: 'ritual-tea-done',
    },
    {
      id: 'mila',
      type: 'npc',
      x: 800,
      spriteKey: 'npc',
      name: 'Мила',
      dialogueId: 'mila-village',
    },
    {
      id: 'kostya-bakery',
      type: 'npc',
      x: 1100,
      spriteKey: 'npc',
      name: 'Пекарь Костя',
      dialogueId: 'kostya-village',
    },
    {
      id: 'yarik',
      type: 'npc',
      x: 1400,
      spriteKey: 'npc',
      name: 'Кузнец Ярик',
      dialogueId: 'yarik-village',
    },
    {
      id: 'tom',
      type: 'npc',
      x: 1800,
      spriteKey: 'npc',
      name: 'Том',
      dialogueId: 'tom-village',
    },
    {
      id: 'polina',
      type: 'npc',
      x: 2200,
      spriteKey: 'npc',
      name: 'Полина',
      dialogueId: 'polina-village',
    },
    {
      id: 'raya',
      type: 'npc',
      x: 2800,
      spriteKey: 'npc',
      name: 'Рая',
      dialogueId: 'raya-village',
    },
    {
      id: 'community-garden',
      type: 'ritual',
      x: 2900,
      spriteKey: 'object',
      name: 'Общинный сад',
      ritualId: 'garden-care',
    },
    {
      id: 'village-cat',
      type: 'examine',
      x: 3200,
      spriteKey: 'npc',
      name: 'Рыжий кот',
      examineText: 'Рыжий кот сидит на бочке у пекарни. Мурчит. Узнал тебя.',
      conditionFlag: 'cat-trusted',
    },
    {
      id: 'exit-to-river',
      type: 'transition',
      x: 3500,
      spriteKey: 'object',
      name: 'Тропа к реке',
      targetLevel: 'quietRiver',
    },
  ],
  palette: {
    bg: '#1e1a14',
    accent: '#E0B87A',
    fog: '#2e2418',
  },
};
