import { LevelData } from './types';

export const foggyGrove: LevelData = {
  id: 'foggyGrove',
  name: 'Туманная роща',
  width: 2800,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 152 },
    { x: 250, y: 150 },
    { x: 500, y: 153 },
    { x: 750, y: 149 },
    { x: 1000, y: 151 },
    { x: 1250, y: 147 },
    { x: 1500, y: 150 },
    { x: 1750, y: 152 },
    { x: 2000, y: 148 },
    { x: 2250, y: 150 },
    { x: 2500, y: 152 },
    { x: 2800, y: 150 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.1 },
    { key: 'bg-trees', scrollFactor: 0.4 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'lost-signpost',
      type: 'examine',
      x: 300,
      spriteKey: 'object',
      name: 'Потерянный указатель',
      examineText: 'Упавший деревянный столб, заросший мхом. Три стрелки — и ни одной надписи. Когда не знаешь, куда идти, любое направление — уже выбор.',
    },
    {
      id: 'vera-grove',
      type: 'npc',
      x: 700,
      spriteKey: 'npc',
      name: 'Вера',
      dialogueId: 'vera-grove',
    },
    {
      id: 'firefly-clearing',
      type: 'ritual',
      x: 1200,
      spriteKey: 'object',
      name: 'Поляна светлячков',
      ritualId: 'firefly-wait',
    },
    {
      id: 'old-hollow',
      type: 'examine',
      x: 1700,
      spriteKey: 'object',
      name: 'Старое дупло',
      examineText: 'В дупле — жестяная коробка. Внутри записка: «Если ты читаешь это — значит, ты не заблудился. Ты просто ещё не нашёл дорогу. Это не одно и то же.» И пучок сухой лаванды.',
    },
    {
      id: 'fedya-postman',
      type: 'npc',
      x: 2100,
      spriteKey: 'npc',
      name: 'Почтальон Федя',
      dialogueId: 'fedya-grove',
    },
    {
      id: 'exit-to-village',
      type: 'transition',
      x: 2700,
      spriteKey: 'object',
      name: 'Тропа к деревне',
      targetLevel: 'fireflyVillage',
    },
  ],
  palette: {
    bg: '#1a1e22',
    accent: '#C9B6D4',
    fog: '#2a2e32',
  },
};
