import { LevelData } from './types';

export const gardenOfSilence: LevelData = {
  id: 'gardenOfSilence',
  name: 'Сад Тишины',
  width: 2800,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 148 },
    { x: 300, y: 146 },
    { x: 600, y: 144 },
    { x: 900, y: 146 },
    { x: 1200, y: 142 },
    { x: 1500, y: 144 },
    { x: 1800, y: 142 },
    { x: 2100, y: 146 },
    { x: 2400, y: 144 },
    { x: 2800, y: 148 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.1 },
    { key: 'bg-trees', scrollFactor: 0.3 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'vera-garden',
      type: 'npc',
      x: 400,
      spriteKey: 'npc',
      name: 'Вера',
      dialogueId: 'vera-garden',
      conditionFlag: 'vera-companion',
    },
    {
      id: 'lin-garden',
      type: 'npc',
      x: 800,
      spriteKey: 'npc',
      name: 'Лин',
      dialogueId: 'lin-garden',
      conditionFlag: 'lin-lesson',
    },
    {
      id: 'central-tree',
      type: 'npc',
      x: 1400,
      spriteKey: 'npc',
      name: 'Отшельник',
      dialogueId: 'hermit-garden',
    },
    {
      id: 'empty-plot',
      type: 'ritual',
      x: 1900,
      spriteKey: 'object',
      name: 'Пустой участок',
      ritualId: 'plant-garden',
    },
    {
      id: 'wall-of-notes',
      type: 'examine',
      x: 2400,
      spriteKey: 'object',
      name: 'Стена записей',
      examineText: 'Часть каменной стены, покрытая надписями. Среди них: «Я был здесь. И мне стало легче.» «Тревога не ушла. Но я научился с ней дышать.» «Тропа не кончается. Она просто меняется.»',
    },
  ],
  palette: {
    bg: '#1a2018',
    accent: '#7C9A7A',
    fog: '#243020',
  },
};
