import { LevelData } from './types';

export const mirrorGrove: LevelData = {
  id: 'mirrorGrove',
  name: 'Роща Зеркал',
  width: 2400,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 152 },
    { x: 300, y: 150 },
    { x: 600, y: 152 },
    { x: 900, y: 148 },
    { x: 1200, y: 150 },
    { x: 1500, y: 152 },
    { x: 1800, y: 148 },
    { x: 2100, y: 150 },
    { x: 2400, y: 152 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.1 },
    { key: 'bg-trees', scrollFactor: 0.3 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'mirror-alley',
      type: 'examine',
      x: 300,
      spriteKey: 'object',
      name: 'Зеркальная аллея',
      examineText: 'Тропа между «зеркальными» деревьями. Каждое показывает чьи-то достижения, чьи-то радости. Чем дольше смотришь — тем тяжелее.',
    },
    {
      id: 'broken-mirror',
      type: 'examine',
      x: 700,
      spriteKey: 'object',
      name: 'Разбитое зеркало',
      examineText: 'Дерево расколото молнией. В осколках — только фрагменты. Рядом надпись: «Чужой путь — только фрагмент. Ты видишь осколок и думаешь, что это целый мир.»',
    },
    {
      id: 'truth-puddle',
      type: 'ritual',
      x: 1100,
      spriteKey: 'object',
      name: 'Лужа правды',
      ritualId: 'truth-puddle',
    },
    {
      id: 'nina-weaver',
      type: 'npc',
      x: 1600,
      spriteKey: 'npc',
      name: 'Ткачиха Нина',
      dialogueId: 'nina-mirrors',
    },
    {
      id: 'zoya-apothecary',
      type: 'npc',
      x: 1350,
      spriteKey: 'npc',
      name: 'Аптекарь Зоя',
      dialogueId: 'zoya-mirrors',
    },
    {
      id: 'mirror-dew',
      type: 'object',
      x: 1800,
      spriteKey: 'object',
      name: 'Зеркальная роса',
      examineText: 'Капли на стволе. В них — только небо. Чистые, без чужих отражений.',
      setFlagOnInteract: 'zoya-dew-collected',
      questVisibility: { questId: 'zoya-dew', phases: ['gathering'] },
    },
    {
      id: 'last-mirror',
      type: 'examine',
      x: 2000,
      spriteKey: 'object',
      name: 'Последнее зеркало',
      examineText: 'Зеркало, которое показывает не чужие, а твои собственные «если бы». Самое трудное. Но ты стоишь здесь — значит, ты уже сильнее, чем думаешь.',
    },
    {
      id: 'exit-to-mountain',
      type: 'transition',
      x: 2300,
      spriteKey: 'object',
      name: 'Тропа в горы',
      targetLevel: 'mountainPath',
    },
  ],
  palette: {
    bg: '#161a22',
    accent: '#C0C8D0',
    fog: '#1e2430',
  },
};
