import { LevelData } from './types';

export const mountainPath: LevelData = {
  id: 'mountainPath',
  name: 'Горная тропа',
  width: 3000,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 160 },
    { x: 300, y: 154 },
    { x: 600, y: 148 },
    { x: 900, y: 142 },
    { x: 1200, y: 136 },
    { x: 1500, y: 130 },
    { x: 1800, y: 126 },
    { x: 2100, y: 132 },
    { x: 2400, y: 128 },
    { x: 2700, y: 124 },
    { x: 3000, y: 120 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.25 },
    { key: 'bg-trees', scrollFactor: 0.5 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'stone-stairway',
      type: 'examine',
      x: 400,
      spriteKey: 'object',
      name: 'Каменная лестница',
      examineText: 'Древняя лестница, вырубленная в скале. Ступени стёрты тысячами ног. На каждой пятой — рисунок: звезда, цветок, сердце, дерево. Кто-то отмечал путь.',
    },
    {
      id: 'hermit-spring',
      type: 'npc',
      x: 900,
      spriteKey: 'npc',
      name: 'Отшельник',
      dialogueId: 'hermit-mountain',
    },
    {
      id: 'cloud-bridge',
      type: 'examine',
      x: 1400,
      spriteKey: 'object',
      name: 'Мост над облаками',
      examineText: 'Каменный мост над ущельем. Внизу — облака. Ты идёшь над облаками. Перехватывает дыхание — не от страха, а от красоты.',
    },
    {
      id: 'echo-cave',
      type: 'ritual',
      x: 1900,
      spriteKey: 'object',
      name: 'Пещера эха',
      ritualId: 'echo-cave',
    },
    {
      id: 'summit-viewpoint',
      type: 'examine',
      x: 2500,
      spriteKey: 'object',
      name: 'Площадка перед вершиной',
      examineText: 'Отсюда виден весь пройденный путь: луга, роща, деревня, река, холмы, зеркальная роща. Всё маленькое, далёкое, но узнаваемое. Ты всё это прошёл.',
    },
    {
      id: 'exit-to-garden',
      type: 'transition',
      x: 2900,
      spriteKey: 'object',
      name: 'Вход в Сад',
      targetLevel: 'gardenOfSilence',
    },
  ],
  palette: {
    bg: '#181c24',
    accent: '#D4C8A0',
    fog: '#222830',
  },
};
