import { LevelData } from './types';

export const quietRiver: LevelData = {
  id: 'quietRiver',
  name: 'Берег Тихой реки',
  width: 3000,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 154 },
    { x: 300, y: 152 },
    { x: 600, y: 156 },
    { x: 900, y: 150 },
    { x: 1200, y: 152 },
    { x: 1500, y: 148 },
    { x: 1800, y: 150 },
    { x: 2100, y: 154 },
    { x: 2400, y: 152 },
    { x: 2700, y: 150 },
    { x: 3000, y: 154 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.12 },
    { key: 'bg-trees', scrollFactor: 0.35 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'willow-arch',
      type: 'examine',
      x: 250,
      spriteKey: 'object',
      name: 'Ивовая арка',
      examineText: 'Две ивы склонились друг к другу, образуя арку. Проходя под ней, чувствуешь, как что-то внутри отпускает — совсем немного, но заметно.',
    },
    {
      id: 'memory-stones',
      type: 'ritual',
      x: 700,
      spriteKey: 'object',
      name: 'Камни памяти',
      ritualId: 'memory-stone',
    },
    {
      id: 'wild-sage',
      type: 'examine',
      x: 750,
      spriteKey: 'object',
      name: 'Дикий шалфей',
      examineText: 'Дикий шалфей у Камней Памяти. Пахнет горько и тепло. Ты срываешь веточку.',
      addItemOnInteract: 'wild-sage',
      questVisibility: { questId: 'mila-tea', phases: ['gathering', 'expired-tired'] },
    },
    {
      id: 'ira',
      type: 'npc',
      x: 1000,
      spriteKey: 'npc',
      name: 'Ира',
      dialogueId: 'ira-meadow',
    },
    {
      id: 'lin',
      type: 'npc',
      x: 1200,
      spriteKey: 'npc',
      name: 'Лин',
      dialogueId: 'lin-river',
    },
    {
      id: 'tikhon-boat',
      type: 'npc',
      x: 1700,
      spriteKey: 'npc',
      name: 'Рыбак Тихон',
      dialogueId: 'tikhon-river',
    },
    {
      id: 'silence-bridge',
      type: 'examine',
      x: 2200,
      spriteKey: 'object',
      name: 'Мост молчания',
      examineText: 'Каменный мост через реку. Негласное правило: на мосту не разговаривают. Только молчат и слушают воду. Кто промолчит — услышит что-то важное.',
    },
    {
      id: 'exit-to-hills',
      type: 'transition',
      x: 2900,
      spriteKey: 'object',
      name: 'Тропа к холмам',
      targetLevel: 'whisperHills',
    },
  ],
  palette: {
    bg: '#141e22',
    accent: '#8AB3B3',
    fog: '#1e2830',
  },
};
