import { LevelData } from './types';

export const quietMeadow: LevelData = {
  id: 'quietMeadow',
  name: 'Тихий Луг',
  width: 3200,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 152 },
    { x: 300, y: 148 },
    { x: 600, y: 150 },
    { x: 900, y: 144 },
    { x: 1200, y: 146 },
    { x: 1500, y: 142 },
    { x: 1800, y: 145 },
    { x: 2100, y: 148 },
    { x: 2400, y: 146 },
    { x: 2700, y: 150 },
    { x: 3000, y: 148 },
    { x: 3200, y: 152 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.15 },
    { key: 'bg-trees', scrollFactor: 0.4 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'meadow-lin',
      type: 'npc',
      x: 600,
      spriteKey: 'npc',
      name: 'Лин',
      dialogueId: 'lin-meadow',
    },
    {
      id: 'singing-stone',
      type: 'examine',
      x: 1000,
      spriteKey: 'object',
      name: 'Поющий камень',
      examineText: 'Гладкий камень, тёплый на ощупь. Если приложить ухо, слышно тихое гудение — не тревожное, а скорее убаюкивающее.',
    },
    {
      id: 'meadow-ritual-flowers',
      type: 'ritual',
      x: 1500,
      spriteKey: 'object',
      name: 'Поляна полевых цветов',
      ritualId: 'flower-gathering',
    },
    {
      id: 'stray-cat',
      type: 'ritual',
      x: 1800,
      spriteKey: 'npc',
      name: 'Рыжий кот',
      ritualId: 'cat-pet',
      conditionNotFlag: 'cat-trusted',
    },
    {
      id: 'ira',
      type: 'npc',
      x: 2200,
      spriteKey: 'npc',
      name: 'Ира',
      dialogueId: 'ira-meadow',
    },
    {
      id: 'exit-to-grove',
      type: 'transition',
      x: 3100,
      spriteKey: 'object',
      name: 'Тропа к роще',
      targetLevel: 'foggyGrove',
    },
  ],
  palette: {
    bg: '#1e2a1e',
    accent: '#a0c878',
    fog: '#2a3a2a',
  },
};
