import { LevelData } from './types';

export const threshold: LevelData = {
  id: 'threshold',
  name: 'Порог',
  width: 2400,
  playerStartX: 80,
  groundLine: [
    { x: 0, y: 150 },
    { x: 200, y: 148 },
    { x: 400, y: 150 },
    { x: 600, y: 146 },
    { x: 800, y: 148 },
    { x: 1000, y: 144 },
    { x: 1200, y: 146 },
    { x: 1400, y: 148 },
    { x: 1600, y: 145 },
    { x: 1800, y: 147 },
    { x: 2000, y: 149 },
    { x: 2200, y: 148 },
    { x: 2400, y: 150 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.2 },
    { key: 'bg-trees', scrollFactor: 0.5 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'old-lantern',
      type: 'examine',
      x: 200,
      spriteKey: 'object',
      name: 'Старый фонарь',
      examineText: 'Тусклый фонарь у тропы. Свет мерцает, но не гаснет — словно кто-то всё ещё заботится о нём.',
    },
    {
      id: 'hermit',
      type: 'npc',
      x: 500,
      spriteKey: 'npc',
      name: 'Отшельник',
      dialogueId: 'hermit-intro',
    },
    {
      id: 'bench',
      type: 'ritual',
      x: 900,
      spriteKey: 'object',
      name: 'Скамейка у ручья',
      ritualId: 'breathing',
    },
    {
      id: 'vera',
      type: 'npc',
      x: 1300,
      spriteKey: 'npc',
      name: 'Вера',
      dialogueId: 'vera-threshold',
    },
    {
      id: 'wilted-flower',
      type: 'ritual',
      x: 1700,
      spriteKey: 'object',
      name: 'Увядший цветок',
      ritualId: 'watering',
    },
    {
      id: 'exit-to-meadow',
      type: 'transition',
      x: 2300,
      spriteKey: 'object',
      name: 'Тропа дальше',
      targetLevel: 'quietMeadow',
    },
  ],
  palette: {
    bg: '#1a1a2e',
    accent: '#c8a870',
    fog: '#2a2a3e',
  },
};
