import { LevelData } from './types';

export const whisperHills: LevelData = {
  id: 'whisperHills',
  name: 'Холмы Шёпота',
  width: 3200,
  playerStartX: 60,
  groundLine: [
    { x: 0, y: 156 },
    { x: 300, y: 150 },
    { x: 600, y: 142 },
    { x: 900, y: 148 },
    { x: 1200, y: 138 },
    { x: 1500, y: 144 },
    { x: 1800, y: 136 },
    { x: 2100, y: 142 },
    { x: 2400, y: 148 },
    { x: 2700, y: 140 },
    { x: 3000, y: 146 },
    { x: 3200, y: 150 },
  ],
  backgrounds: [
    { key: 'bg-sky', scrollFactor: 0 },
    { key: 'bg-mountains', scrollFactor: 0.2 },
    { key: 'bg-trees', scrollFactor: 0.45 },
    { key: 'bg-ground', scrollFactor: 1 },
  ],
  interactables: [
    {
      id: 'first-hill-top',
      type: 'examine',
      x: 400,
      spriteKey: 'object',
      name: 'Вершина Первого холма',
      examineText: 'Отсюда видно всё: луга, рощу, деревню, реку. Впервые видишь тропу целиком — и понимаешь, сколько уже прошёл.',
    },
    {
      id: 'wind-harp',
      type: 'ritual',
      x: 900,
      spriteKey: 'object',
      name: 'Ветряная арфа',
      ritualId: 'wind-harp',
    },
    {
      id: 'hermit-cave',
      type: 'npc',
      x: 1500,
      spriteKey: 'npc',
      name: 'Отшельник',
      dialogueId: 'hermit-hills',
    },
    {
      id: 'sol-tree',
      type: 'npc',
      x: 2200,
      spriteKey: 'npc',
      name: 'Сол',
      dialogueId: 'sol-hills',
    },
    {
      id: 'stargazer-mark',
      type: 'npc',
      x: 2700,
      spriteKey: 'npc',
      name: 'Звездочёт Марк',
      dialogueId: 'mark-hills',
    },
    {
      id: 'exit-to-mirrors',
      type: 'transition',
      x: 3100,
      spriteKey: 'object',
      name: 'Тропа к роще',
      targetLevel: 'mirrorGrove',
    },
  ],
  palette: {
    bg: '#1a1822',
    accent: '#B8A8C4',
    fog: '#2a2832',
  },
};
